PLUGIN_NAME=		wancarp
PLUGIN_VERSION=		1.0.0
PLUGIN_COMMENT=		WAN CARP Hook – enable/disable WAN on CARP failover
PLUGIN_MAINTAINER=	your@email.com
PLUGIN_WWW=		https://github.com/chefkoch-de42/opnsense-plugins

.include "../../Mk/plugins.mk"

