#!/usr/local/bin/php
<?php
/*
 * Copyright (C) 2024 Your Name
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

require_once("config.inc");
require_once("interfaces.inc");
require_once("util.inc");
require_once("system.inc");

$subsystem = !empty($argv[1]) ? $argv[1] : '';
$type      = !empty($argv[2]) ? $argv[2] : '';

if (!in_array($type, ['MASTER', 'BACKUP', 'INIT'])) {
    log_msg("wancarp: unknown CARP event type '{$type}' from '{$subsystem}'");
    exit(1);
}

if (!strstr($subsystem, '@')) {
    log_error("wancarp: CARP event '{$type}' triggered from wrong source '{$subsystem}'");
    exit(1);
}

// Load plugin settings from model
$settings = new \OPNsense\WanCarp\General();

$enabled = (string)$settings->enabled === '1';
if (!$enabled) {
    exit(0);
}

$ifkey  = (string)$settings->ifkey;
$vhid   = (string)$settings->vhid;

if (empty($ifkey)) {
    log_error("wancarp: no interface configured, aborting.");
    exit(1);
}

// Only act when the configured VHID triggers (or if vhid is empty = act on all)
if (!empty($vhid) && !preg_match('/^' . preg_quote($vhid, '/') . '@/', $subsystem)) {
    exit(0);
}

$real_if = get_real_interface($ifkey);

if ($type === 'MASTER') {
    log_error("wancarp: enabling interface '{$ifkey}' ({$real_if}) due to CARP event '{$type}' on '{$subsystem}'");
    $config['interfaces'][$ifkey]['enable'] = '1';
    write_config("wancarp: enable interface '{$ifkey}' due to CARP event '{$type}'", false);
    interface_configure(false, $ifkey, false, false);
    sleep(2);
    shell_exec("/sbin/ifconfig " . escapeshellarg($real_if) . " up");
    log_msg("wancarp: issuing interface_configure on '{$real_if}' to request a DHCP lease");
    sleep(1);
    interface_configure(false, $ifkey, false, false);
} else {
    log_error("wancarp: disabling interface '{$ifkey}' ({$real_if}) due to CARP event '{$type}' on '{$subsystem}'");
    unset($config['interfaces'][$ifkey]['enable']);
    write_config("wancarp: disable interface '{$ifkey}' due to CARP event '{$type}'", false);
    interface_configure(false, $ifkey, false, false);
    shell_exec("/sbin/ifconfig " . escapeshellarg($real_if) . " down");
}

